#!/usr/bin/env bash
# mcp-environment/setup-codex-mcp.sh — sync repo MCP config into ~/.codex/config.toml
#
# Compatible macOS and Linux. This keeps Codex MCP setup reproducible in the
# same spirit as claude-environment/setup.sh.

set -euo pipefail

ENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="${ENV_DIR}/codex.config.toml"
DST="${HOME}/.codex/config.toml"
BACKUP="${HOME}/.codex/config.toml.backup-$(date +%Y%m%d-%H%M%S)"
BEGIN="# >>> patasyhogar mcp-environment"
END="# <<< patasyhogar mcp-environment"

if [[ ! -f "${SRC}" ]]; then
  echo "ERROR: no encuentro ${SRC}" >&2
  exit 1
fi

mkdir -p "$(dirname "${DST}")"
touch "${DST}"
cp "${DST}" "${BACKUP}"

TMP="$(mktemp)"
GENERATED="$(mktemp)"
awk -v begin="${BEGIN}" -v end="${END}" '
  $0 == begin { skip = 1; next }
  $0 == end { skip = 0; next }
  skip != 1 { print }
' "${DST}" > "${TMP}"

cp "${SRC}" "${GENERATED}"

GOOGLE_ADC="${GOOGLE_APPLICATION_CREDENTIALS:-${HOME}/.config/gcloud/application_default_credentials.json}"
GOOGLE_PROJECT="${GOOGLE_PROJECT_ID:-patasyhogar-mcp}"
CLOUDFLARE_TOKEN="${CLOUDFLARE_API_TOKEN:-}"
CLOUDFLARE_STATUS="no detectado; exportalo antes de ejecutar este setup"
OS_NAME="$(uname -s 2>/dev/null || echo unknown)"
SHELL_NAME="$(basename "${SHELL:-}")"
SHELL_HINT="exporta las variables en el perfil de la shell que lance Codex"

case "${OS_NAME}:${SHELL_NAME}" in
  Darwin:zsh)
    SHELL_HINT="macOS/zsh: usa ~/.zshrc para shells interactivas y ~/.zprofile si Codex se lanza desde una shell login"
    ;;
  Darwin:bash)
    SHELL_HINT="macOS/bash: usa ~/.bash_profile para shells login y ~/.bashrc para shells interactivas"
    ;;
  Linux:zsh)
    SHELL_HINT="Linux/zsh: usa ~/.zshrc para shells interactivas y ~/.zprofile si Codex se lanza desde una shell login"
    ;;
  Linux:bash)
    SHELL_HINT="Linux/bash: usa ~/.bashrc y asegurate de que ~/.bash_profile o ~/.profile lo cargue en shells login"
    ;;
esac

toml_escape() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

if [[ -n "${CLOUDFLARE_TOKEN}" ]]; then
  CLOUDFLARE_STATUS="detectado y escrito como header local en ~/.codex/config.toml"
  FILTERED="$(mktemp)"
  awk '
    $0 ~ /^[[:space:]]*bearer_token_env_var[[:space:]]*=/ { next }
    { print }
  ' "${GENERATED}" > "${FILTERED}"
  mv "${FILTERED}" "${GENERATED}"

  CLOUDFLARE_AUTH_HEADER="Bearer ${CLOUDFLARE_TOKEN}"
  cat >> "${GENERATED}" <<EOF

# Local machine value generated by setup-codex-mcp.sh. This stores the
# Cloudflare bearer header in ~/.codex/config.toml (chmod 600) because some
# Codex launch paths do not inherit shell variables early enough for remote
# MCP auth.
[mcp_servers.cloudflare-api.http_headers]
Authorization = "$(toml_escape "${CLOUDFLARE_AUTH_HEADER}")"
EOF
fi

if [[ -f "${GOOGLE_ADC}" ]]; then
  FILTERED="$(mktemp)"
  awk '
    $0 ~ /^[[:space:]]*env_vars[[:space:]]*=/ { next }
    { print }
  ' "${GENERATED}" > "${FILTERED}"
  mv "${FILTERED}" "${GENERATED}"

  cat >> "${GENERATED}" <<EOF

# Local machine values generated by setup-codex-mcp.sh. These are paths/project
# identifiers, not credential contents, and keep Google MCPs working even when
# Codex is launched without inheriting shell startup files.
[mcp_servers.google-analytics.env]
GOOGLE_APPLICATION_CREDENTIALS = "${GOOGLE_ADC}"
GOOGLE_PROJECT_ID = "${GOOGLE_PROJECT}"

[mcp_servers.google-search-console.env]
GOOGLE_APPLICATION_CREDENTIALS = "${GOOGLE_ADC}"
EOF
else
  cat >&2 <<EOF
WARNING: no encuentro credenciales ADC en:
  ${GOOGLE_ADC}

Google Analytics y Search Console dependeran de que Codex herede:
  GOOGLE_APPLICATION_CREDENTIALS
  GOOGLE_PROJECT_ID
EOF
fi

{
  sed '/^[[:space:]]*$/N;/^\n$/D' "${TMP}"
  echo
  echo "${BEGIN}"
  cat "${GENERATED}"
  echo "${END}"
} > "${DST}"

rm -f "${TMP}" "${GENERATED}"
chmod 600 "${DST}"

cat <<EOF
Codex MCP config sincronizada:
  ${DST}

Backup:
  ${BACKUP}

Reinicia Codex para cargar los MCP.
Autenticacion Cloudflare para Codex:
  CLOUDFLARE_API_TOKEN ${CLOUDFLARE_STATUS}
  ${SHELL_HINT}

Google Analytics usa Application Default Credentials:
  GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_ADC}
  GOOGLE_PROJECT_ID=${GOOGLE_PROJECT}
EOF
